#!/usr/bin/env python3
"""
Weekly Sync Script for Instagram Archive

Incrementally syncs new posts and generates weekly asset report
for the 01-input stage.

Usage:
    python sync-weekly.py

Output:
    - Updates instagram/data/archive/cerafica_archive.json
    - Creates instagram/stages/01-input/output/weekly-assets-[date].md
"""

import sys
from datetime import datetime, timedelta
from pathlib import Path

# Add lib to path
sys.path.insert(0, str(Path(__file__).parent / "lib"))

import instaloader
from instaloader_utils import (
    get_instaloader_instance,
    get_archive_path,
    get_media_dir,
    load_archive,
    save_archive,
    update_sync_timestamp,
    get_last_sync_timestamp,
    post_to_dict,
    get_workspace_root,
)


def get_new_posts(username: str = "cerafica_design", since: datetime = None) -> list[dict]:
    """
    Get posts since a specific date.

    Args:
        username: Instagram username
        since: Only get posts after this date

    Returns:
        List of new posts
    """
    L = get_instaloader_instance()

    print(f"Checking @{username} for new posts...")
    profile = instaloader.Profile.from_username(L.context, username)

    new_posts = []
    total_checked = 0

    for post in profile.get_posts():
        total_checked += 1

        # Stop if we've reached posts older than our threshold
        if since and post.date_local < since:
            print(f"\n  Reached posts from before {since.date()}, stopping.")
            break

        new_posts.append(post_to_dict(post))
        print(f"\r  Checked {total_checked} posts, found {len(new_posts)} new", end="")

    print()

    return new_posts


def generate_weekly_assets_report(new_posts: list[dict], output_dir: Path) -> Path:
    """Generate the weekly assets markdown report."""

    date_str = datetime.now().strftime("%Y-%m-%d")
    output_path = output_dir / f"weekly-assets-{date_str}.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    md = f"""# Weekly Assets Report

Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}
New posts: {len(new_posts)}

---

"""

    if not new_posts:
        md += """## No New Posts

No new posts detected since the last sync.

### Next Steps

- Continue with existing content pipeline
- Check back next week
- Or manually add assets to this folder

"""
    else:
        md += """## New Posts This Week

"""

        for i, post in enumerate(new_posts, 1):
            caption = post.get("caption", "") or "No caption"
            hashtags = post.get("hashtags", [])

            md += f"""### Post {i}: [{post['shortcode']}]({post['url']})

**Posted:** {post['date'][:10]}
**Type:** {'Video' if post.get('is_video') else 'Carousel' if post.get('mediacount', 1) > 1 else 'Image'}
**Engagement:** {post.get('likes', 0):,} likes, {post.get('comments', 0):,} comments

**Caption:**
> {caption[:200]}{'...' if len(caption) > 200 else ''}

**Hashtags:** {' '.join(['#' + t for t in hashtags[:10]])}

**Media:** `instagram/data/archive/cerafica_media/`

---

"""

        md += f"""## Summary

- **New posts:** {len(new_posts)}
- **Total engagement:** {sum(p.get('likes', 0) + p.get('comments', 0) for p in new_posts):,}
- **Average likes:** {sum(p.get('likes', 0) for p in new_posts) // len(new_posts):,}

### Content Ideas for This Week

Based on this week's posts:

"""

        # Generate content ideas based on posts
        if new_posts:
            md += """1. Consider reposting high-performing content to Stories
2. Create Reel from video content
3. Share behind-the-scenes of most-liked post
"""

    md += f"""
---

*Auto-generated by `scripts/sync-weekly.py`*
*Next sync recommended: {(datetime.now() + timedelta(days=7)).strftime("%Y-%m-%d")}*
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(md)

    return output_path


def sync_archive(username: str = "cerafica_design") -> dict:
    """
    Sync the archive with new posts.

    Returns:
        Dictionary with sync results
    """
    print("\n" + "=" * 60)
    print("WEEKLY INSTAGRAM SYNC")
    print("=" * 60 + "\n")

    # Load existing archive
    archive_path = get_archive_path()
    if archive_path.exists():
        archive = load_archive()
        existing_shortcodes = {p["shortcode"] for p in archive.get("posts", [])}
        print(f"Existing archive: {len(existing_shortcodes)} posts")
    else:
        archive = {"metadata": {}, "posts": []}
        existing_shortcodes = set()
        print("No existing archive found, will create new one.")

    # Get last sync timestamp
    last_sync = get_last_sync_timestamp()
    if last_sync:
        print(f"Last sync: {last_sync.strftime('%Y-%m-%d %H:%M')}")
    else:
        print("No previous sync found, will fetch all posts.")

    # Get new posts
    print()
    new_posts = get_new_posts(username, since=last_sync)

    # Filter out already-archived posts
    truly_new = [p for p in new_posts if p["shortcode"] not in existing_shortcodes]

    print(f"\nFound {len(truly_new)} new posts to add.")

    # Download media for new posts
    if truly_new:
        print("\nDownloading media for new posts...")
        L = get_instaloader_instance()
        media_dir = get_media_dir()
        media_dir.mkdir(parents=True, exist_ok=True)

        profile = instaloader.Profile.from_username(L.context, username)

        for i, post_data in enumerate(truly_new, 1):
            print(f"  [{i}/{len(truly_new)}] Downloading {post_data['shortcode']}...")

            try:
                # Find the post object
                for post in profile.get_posts():
                    if post.shortcode == post_data["shortcode"]:
                        L.download_post(post, target=media_dir)
                        break
            except Exception as e:
                print(f"    Warning: Could not download: {e}")

    # Add new posts to archive
    archive["posts"].extend(truly_new)

    # Sort by date (newest first)
    archive["posts"].sort(key=lambda x: x.get("date", ""), reverse=True)

    # Update metadata
    archive["metadata"]["last_sync"] = datetime.now().isoformat()
    archive["metadata"]["total_posts"] = len(archive["posts"])

    # Save archive
    save_archive(archive)
    update_sync_timestamp()

    print(f"\n✓ Archive updated: {archive_path}")

    return {
        "new_posts": len(truly_new),
        "total_posts": len(archive["posts"]),
        "archive": archive,
    }


def main():
    """Main entry point."""
    print("\n" + "=" * 60)
    print("CERAMICS INSTAGRAM WEEKLY SYNC")
    print("=" * 60 + "\n")

    try:
        # Sync archive
        result = sync_archive()

        # Generate weekly report
        print("\nGenerating weekly assets report...")
        output_dir = get_workspace_root() / "instagram/stages" / "01-input" / "output"
        report_path = generate_weekly_assets_report(
            result["archive"]["posts"][:result["new_posts"]] if result["new_posts"] else [],
            output_dir,
        )

        print(f"✓ Weekly report: {report_path}")

        # Summary
        print("\n" + "=" * 60)
        print("SYNC COMPLETE")
        print("=" * 60)
        print(f"New posts: {result['new_posts']}")
        print(f"Total archived: {result['total_posts']}")
        print(f"Report: {report_path}")

        if result["new_posts"] == 0:
            print("\nNo new content to process this week.")
        else:
            print(f"\n→ Next step: Run content planning in 02-planning")

    except Exception as e:
        print(f"\nError: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
